query ListProducts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products {
    id
    name
    description
    price
  }
}

query GetUserProfile @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  users(where: {id: {eq_expr: "auth.uid"}}) {
    id
    username
    email
  }
}

mutation CreateOrder($productId: String!, $quantity: Int!) @auth(level: USER) {
  orders_insert(data: {
    userId_expr: "auth.uid",
    productId: $productId,
    quantity: $quantity
  })
}

mutation UpdateProductPrice($id: String!, $newPrice: Float!) @auth(expr: "auth.token.admin == true") {
  products_update(key: {id: $id}, data: {
    price: $newPrice
  })
}